### ISSUE TITLE
Windows server 2016

### ISSUE THREAD

**Issue by thisistheredteam** [atlantsecurity/windows-hardening-scripts#1]
Not an issue but questions rather than an issue.

Would the 2019 hardening script work for 2016 windows server?

**Comment by atlantsecurity** [comment]
You should focus your server hardening efforts on DISA STIG GPOs available on the DISA website. My script for 2016/2019 is very, VERY basic.

**Comment by thisistheredteam** [comment]
It seemingly covers most important findings from my DISA STIG OpenSCAP findings.
But it's a clean server afterall.

**Comment by thalesredteam** [comment]
So you think it will work fine for 2016 to?

**Comment by atlantsecurity** [comment]
it should.

**Comment by thisistheredteam** [comment]
Thanks for quick response.
Have a nice day.
