### ISSUE TITLE
Whole project as issue

### ISSUE THREAD

**Issue by Ricky-Tigg** [atlantsecurity/windows-hardening-scripts#3]
Sure that some people do know how to waste their time. What is certain is that you know something about it. Invariably, attempts to make of a strongly established bad-designed platform a one bit less bad, end in failures. Can't you see you added a new variant of a misleading discourse "_A collection of Windows (...) hardening scripts_", revealing at best your lack of understanding of global context. Windows, if not none, is the one beyond the scope of being a suitable target to be hardened healthily. Hardening on faulty ground is not meant to do anything but to fail. The sooner you learn it, the better.

**Comment by atlantsecurity** [comment]
ROFL
