### ISSUE TITLE
Windows 11 Script Incompatibility with OSArmor?

### ISSUE THREAD

**Issue by ghost** [atlantsecurity/windows-hardening-scripts#5]
Thanks much for that restore point, because it saved my machine from being bricked...

After a variable number of restarts after application of the script in Win 11, on the first restart OSArmor is either present for a time or crashes and OSArmor prompts to restart. If not so, then it takes an additional restart.

After that restart, the computer sometimes will refuse to load anything... Task bar doesn't work, sometimes windows explorer will launch after 5 minutes, sometimes after a time a white screen, start menu fails, win+run works but doesn't launch anything.

Only a roll back works.

I've tried this a total now of 5 times, running the script is the culprit in this scenario and how it mixes with my system.

Note that I only run the bat with OSAmor disabled. Once completed, I enable it again.

Because of the OSArmor crash and failure that only happens in between restarts, I can only guess maybe somehow that is related?

Here's some "hardening" I've used:

DNS Encryption
Custom Group Policy Editor Changes
BitDefender
OOSU10
SysHardener
OSArmor - Extreme Profile
TinyWall
Windows-11-hardening-script.bat

**Comment by atlantsecurity** [comment]
Your inability to mix and match security solutions is not an issue of this script. It works flawlessly on a clean system. What you decide to add on top of it (or below it) is your problem.
